name: Publish NuGet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: pwsh

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        cd src/KahulUI
        dotnet restore
    - name: Build solution and generate NuGet package
      run: |  
        cd src/KahulUI
        dotnet build -c Release
        dotnet pack -c Release -o out
    - name: Publish nuget
      run: |
        cd src/KahulUI
        foreach($file in (Get-ChildItem "out" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }